spring:
  main:
    banner-mode: off
  datasource:    url: jdbc:mysql://localhost:3306/spring-reddit-clone
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization: true 
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:    host: smtp.mailtrap.io
    port: 25
    username: 88ca9b0b870e44
    password: 9918de57d6a50e 
    protocol: smtp
jwt:
  expiration:
    time: 90000
management:  endpoints:    web:      exposure:        include: "*"
      base-path: /
  security:
    enabled: false
